### ISSUE TITLE
Insert copyright notice as PHP comment, not HTML

### ISSUE THREAD

**Issue by molovo** [lee-dohm/auto-copyright#19]
In a PHP class, the comment is added as a HTML comment before the opening `<?php` tag ([screenshot](https://cloud.githubusercontent.com/assets/2746289/20298481/119b459e-ab0e-11e6-9a19-b66d51888ac6.png)
). This results in headers being sent to the browser early as the comment is printed to the screen, rather than being hidden in the source code. Also makes CLI apps unusable as the HTML output appears in `stdout`.

This could just be because it's being added before the first line, and in that location a HTML comment *is* the correct thing to put, but probably worth checking the current syntax and bumping it down a line if it's PHP.

**Comment by lee-dohm** [comment]
This package is no longer maintained. All issues and PRs have been closed and [the repository has been archived.](https://help.github.com/articles/about-archiving-repositories/) This is remaining published in the Atom package repository so that people can find it to fork it and create their own version. Hopefully one of them will create a new maintained version.
