### ISSUE TITLE
More custom fields

### ISSUE THREAD

**Issue by ericrange** [lee-dohm/auto-copyright#4]
Can you add more custom fields to the copyright area?

eg.
-license
-current filename
-last changed
-url (of the project)
-name (of the project)
-...

maybe you could get the project info from package.json?

**Comment by nipunarora** [comment]
I second these changes as well, will be super helpful, with support from other packages. Check out the following package in sublime - https://packagecontrol.io/packages/FileHeader, or alternatively make-header in emacs. It's a common thing in most editors and would be very helpful :)

-license
- author 
-current filename
- date and time created
-last changed
-url (of the project)
-name (of the project)
- description:

**Comment by envygeeks** [comment]
@lee-dohm @ericrange that doesn't work on Linux because DFSG and Package Guidelines for Ubuntu/Debian/Fedora require a license and copyright header in every file of a package (that is not a binary) because how are you to know the copyright of everything spread across a system? Sure you could check out /usr/share/package/COPYRIGHT but yeah obvious is obvious.  I'm pretty sure even OS X has the same guideline for software that they provide from the free/open realm just because it simplifies life.

I'm not here for that though because that is irrelevant to us, we worked around that already... I'm here to ask for a way to customize the comment style itself, we like to add headers to comments to make them stand out more so it would be nice if we could adjust the first and last comment.

```
# What I want to change.
# Data.
# What I want to change.
```

**Comment by lee-dohm** [comment]
This package is no longer maintained. All issues and PRs have been closed and [the repository has been archived.](https://help.github.com/articles/about-archiving-repositories/) This is remaining published in the Atom package repository so that people can find it to fork it and create their own version. Hopefully one of them will create a new maintained version.
